version: 0.2 
 
phases: 
  pre_build: 
    commands: 
      - echo Generating image tag from git hash
      - IMAGE_TAG=`git log -1 --format=%h`
      - COMMIT_ID=`git log -1 --format=%H`
      - echo Logging in to Amazon ECR... 
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION) 
  build: 
    commands: 
      - echo Build started on `date` 
      - echo Building the Docker image...           
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG . 
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG       
  post_build: 
    commands: 
      - echo Build completed on `date` 
      - echo Pushing the Docker image... 
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Dinamically updating image tag in kubernetes manifest
      - sed -i.bak "s/DynamicImageTagFromBuild/$IMAGE_TAG/g" manifests/demo.yml
      - rm manifests/demo.yml.bak
      - echo "{"name":"manifests/demo.yml","reference":"https://api.github.com/repos/kornelbicskei/spin-kub-v2-demo/contents/manifests/demo.yml","type":"github/file","version":"GitCommit"}" > artifact.properties
      - ls -alt
      - sed -i.bak "s/GitCommit/$COMMIT_ID/g" artifact.properties
      - rm artifact.properties.bak
