
apiVersion: extensions/v1beta1 # 1for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: codesuite-demo
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello
        image: index.docker.io/corneelius/spin-kub-v3-demo:release-master
        ports:
        - containerPort: 80
