apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-demo-config
  namespace: default
data:
  NEW_FEATURE: "true"

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: spinnaker-demo
  namespace: default
  labels:
    source: demo
    stack: frontend
    app: spinnaker
spec:
  replicas: 3
  selector:
    matchLabels:
      source: demo
      app: spinnaker
  template:
    metadata:
      labels:
        source: demo
        app: spinnaker
    spec:
      containers:
      - name: primary
        image: index.docker.io/lwander/spin-kub-v2-demo
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        envFrom:
        - configMapRef:
            name: spinnaker-demo-config

---

kind: Service
apiVersion: v1
metadata:
  name: spinnaker-demo
  namespace: default
spec:
  selector:
    source: demo
    app: spinnaker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort

 ---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spinnaker-demo
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: spinnaker-demo-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: spinnaker-demo
              servicePort: 80
