
apiVersion: extensions/v1beta1 # 1for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: codesuite-demo
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello
        image: index.docker.io/corneelius/spin-kub-v3-demo:release-master
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---

kind: Service
apiVersion: v1
metadata:
  name: codesuite-demo
spec:
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: codesuite-demo
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: hello-world
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: codesuite-demo
              servicePort: 80
